### ISSUE TITLE
Don't use arrays for converters in JsonSerializerSettings instances

### ISSUE THREAD

**Issue by atsapura** [microsoft/fsharplu#100]
There's number of places  like [this](https://github.com/microsoft/fsharplu/blob/master/FSharpLu.Json/Compact.fs#L501) where you use `Converters = [|CompactUnionJsonConverter(true, true)|]`.

Problem is some extension methods like `ConfigureForNodaTime` adjust existing settings with `settings.Converters.Add(...)`, which leads to a `NotSupportedException` being thrown.

Solution is very easy and here are some options:

```fsharp
let converters = ResizeArray([CompactUnionJsonConverter(true, false) :> JsonConverter])
JsonSerializerSettings(Converters = converters)

// or

let settings = JsonSerializerSettings(...)
settings.Converters.Add(CompactUnionJsonConverter(true, false))
settings
```

**Comment by blumu** [comment]
@atsapura Thank you for reporting. Would you consider submitting a pull request with the fix?
