### ISSUE TITLE
Is it possible to serialize DU cases in camelCase instead of PascalCase?

### ISSUE THREAD

**Issue by pmbanka** [Microsoft/fsharplu#16]
camelCase serialization is mentioned in [this issue](https://github.com/Microsoft/fsharplu/issues/8) and provided fix works nicely for records, but not for discriminated unions. Example:

```
#r "packages/Microsoft.FSharpLu.Json/lib/net452/Microsoft.FSharpLu.Json.dll" 
#r "packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll" 

open System
open Microsoft.FSharpLu.Json
open Newtonsoft.Json

type Settings =
    static member settings =
        let s = 
            JsonSerializerSettings(
                NullValueHandling = NullValueHandling.Ignore,
                MissingMemberHandling = MissingMemberHandling.Error,
                ContractResolver = Serialization.CamelCasePropertyNamesContractResolver())
        s.Converters.Add(CompactUnionJsonConverter())
        s
    static member formatting = Formatting.None

type MyCamlCaseSerializer = With<Settings>

type Record = { First : int; Second : int }
type DU = | FancyCase of Record

MyCamlCaseSerializer.serialize <| FancyCase { First = 0; Second = 1 }
```

returns

```
val it : string =
  "{
  "FancyCase": {
    "first": 0,
    "second": 1
  }
}"
```
Is there a way to override this behaviour? (from skimming the code it seems to me that there is not)

**Comment by blumu** [comment]
This is a bug: the code that processes discriminated unions does not honor the [`DefaultContractResolvers`](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_DefaultContractResolver.htm) configured in the JSon.Net settings. Here is what would need to be modified to fix it:
- Define a function `processWithContractResolvers : string -> string` that iterates over all the property name contract resolvers configured with Json.Net and call the corresponding [`ResolvePropertyName`](http://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Serialization_DefaultContractResolver_ResolvePropertyName.htm) method.
- [Compact.fs, line81](https://github.com/Microsoft/fsharplu/blob/master/FSharpLu.Json/Compact.fs#L81). Replace:
`writer.WritePropertyName(case.Name)`
 with 
`writer.WritePropertyName(processWithContractResolvers case.Name)`
- Same [line 87](https://github.com/Microsoft/fsharplu/blob/master/FSharpLu.Json/Compact.fs#L87)
- Similarly for deserialization, in [Compact.fs, Line 185](https://github.com/Microsoft/fsharplu/blob/master/FSharpLu.Json/Compact.fs#L175). Replace
```
|> Seq.tryFind (fun case -> case.Name.Equals(caseProperty.Name, System.StringComparison.InvariantCultureIgnoreCase))
```
by
```
|> Seq.tryFind (fun case -> (processWithContractResolvers case.Name).Equals(caseProperty.Name, System.StringComparison.InvariantCultureIgnoreCase))
```

**Comment by pmbanka** [comment]
Thanks for the explanation! I'll submit a PR :)

**Comment by blumu** [comment]
Closing issue. Thanks for the PR @pmbanka

**Comment by pmbanka** [comment]
Thanks for guiding me through the process @blumu :)
