### ISSUE TITLE
Json: convert tuples to arrays

### ISSUE THREAD

**Issue by vivainio** [Microsoft/fsharplu#31]
Currently, even Compact json serialization outputs tuples as multi-element objects

```
{
    "Item1": "foo",
    "Item2": 12
}
```

It should output ["foo", 12]. Implementation exists e.g. in https://github.com/haf/Newtonsoft.Json.FSharp (but that project is deprecated)

**Comment by blumu** [comment]
Working on it as part of Microsoft Hackathon project. Branch: https://github.com/Microsoft/fsharplu/tree/wiblum/hackathon @vivainio
