### ISSUE TITLE
NullReferenceException on Discriminated Union serialization

### ISSUE THREAD

**Issue by kagetoki** [microsoft/fsharplu#39]
Consider DU:
```
type Claim = Read | Edit | Delete | Custom of string
```
Sometimes during serialization I get `NullReferenceException`, no matter the case.
Issue is present both for compact and standard modes.
It's a floating issue, I haven't noticed any pattern of it's reproducing

**Comment by blumu** [comment]
@kagetoki Closing this old bug. Feel free to reopen if this still reproes and if you can provide the requested information.
