### ISSUE TITLE
Unable to run project because fsharplu cause a downgrade (broken build)

### ISSUE THREAD

**Issue by mamcx** [microsoft/fsharplu#40]
I have a issue that with recent versions of FSharp.Core FSharpLu broke my builds. It get this error:

```
   /Core.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 4.3.4 to 4.2.0. Reference the package directly from the project to select a different version. 
    Core.fsproj : warning NU1605:  Core (>= 1.0.0) -> Microsoft.FSharpLu (>= 0.10.26) -> FSharp.Core (>= 4.3.4) 
```

**Comment by blumu** [comment]
@mamcx  Have you tried building with the latest version of VS with F# 4.3.4? Could you also provide a minimum repro?

**Comment by blumu** [comment]
@mamcx Closing this bug since there is no repro steps to investigate.
