### ISSUE TITLE
Not deserialize with culture invariant?

### ISSUE THREAD

**Issue by mamcx** [Microsoft/fsharplu#56]
I'm trying to read json with financial info like:

`{"cost": 0.0, "price": 417.0, "total": 834.0, "doc_id": 2, "status": "Sync", "doc_code": "ORD-5-1", "doc_kind": "O", "username": "02", "createdat": "2019-01-02T17:09:48.478918", "sub_total": 834.0, "tax_value": 0.0, "updatedat": "2019-01-02T17:10:08.00777-05:00", "customer_code": "43915888_37", "delivery_order": 0, "discount_value": 0.0}`

But it return, for example:

```
"cost": 0.0 //json
cost: 281474976710656 //.NET
```

This happened if the locale of the iOS device is set to Spanish/Colombia. On US locale it work. The weird thing is that is supposed to work with invariant culture:

https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_Culture.htm

I try to change in the code:

```f#
    module Internal =
        /// Serialization settings for the default NetwonSoft Json.Net's serialization format
        type DefaultSettings =
            static member settings =
                let s = JsonSerializerSettings(NullValueHandling = NullValueHandling.Ignore, Culture= System.Globalization.CultureInfo.InvariantCulture)
                s.Converters.Add(Converters.StringEnumConverter())
                s
            static member formatting = Formatting.Indented
//called with
let inline fromJson< ^T> x : ^T  =
    Json.BackwardCompatible.deserialize x
```

but don't see a change.

**Comment by mamcx** [comment]
Ok, but that is for compare strings, where is affected the handling of numbers? I need to fix this, I have the app in production and the financial data is broken.

**Comment by blumu** [comment]
@mamcx Do you repro when deserializing directly with Newtonsoft.Json?

**Comment by blumu** [comment]
@mamcx  Could you also share a full repro, including the actual type used for deserialization?

**Comment by mamcx** [comment]
The problem can be see with just:

```f#
type DocumentRow = {
    doc_id:int32
    doc_kind:string
    doc_code:string
    customer_code:string
    from_code:string option
    username:string
    createdat:DateTime
    updatedat:DateTime
    dueat:DateTime option
    signature:string option
    authorized:string option
    delivery_order:int32
    price:decimal
    cost:decimal
    tax_value:decimal
    discount_value:decimal
    sub_total:decimal
    total:decimal
    status:string
    notes:string option
    syncdata:string option
    version:int32
}
```

**Comment by blumu** [comment]
@mamcx We would need more info to look at this bug as per previous questions. Could you provide the following:
- Does it repro when deserializing directly with Newtonsoft.Json?
- Does it repro on Windows?
- Does it repro on .net framwork or dotnetcore?
- Could you also share a full repro, including the actual type used for deserialization?
