### ISSUE TITLE
registerFileAndConsoleTracer file redirection not working in netcoreapp2.1 app

### ISSUE THREAD

**Issue by marina-p** [Microsoft/fsharplu#57]
I modified the main function in FSharpLu.Windows.Sample.fsproj (current version in master) to also redirect output to a file, as follows, ran the app and it did not produce any file output.

    use logger = System.Diagnostics.Listener.registerFileAndConsoleTracer "myComponentName" (Some @"d:\temp")

**Comment by blumu** [comment]
@marina-p This is caused by a bug in `System.Diagnostics.TextWriterTraceListener`. I filed it at https://github.com/dotnet/corefx/issues/35866 I will send a workaround shortly.
