### ISSUE TITLE
How can I serialize with json keys in camelcase?

### ISSUE THREAD

**Issue by rubedojr** [Microsoft/fsharplu#8]
How can I serialize with the json keys in camelcase instead of the default pascalcase?
This: { someKey: "value" }
instead of: { SomeKey: "value" }

**Comment by blumu** [comment]
This can be done by specifying your custom Json.Net serialization settings to the 'With' functor using  the `CamelCasePropertyNamesContractResolver` [contract resolver](http://www.newtonsoft.com/json/help/html/ContractResolver.htm). It would go something like (untested):
```
open Newtonsoft.Json
type Settings =
    static member settings =
        let s = JsonSerializerSettings(
                    NullValueHandling = NullValueHandling.Ignore,
                    MissingMemberHandling = MissingMemberHandling.Error
                    ContractResolver = new Serialization.CamelCasePropertyNamesContractResolver())
        s.Converters.Add(CompactUnionJsonConverter())
        s
    static member formatting = Formatting.None

type MyCamlCaseSerializer = With<Internal.Settings>

MyCamlCaseSerializer.serialize [ "bla" ]
```
